/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "esp_hosted_config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SCAN_RESULT, scan_result_t, AUTO)


PB_BIND(CONNECTED_STA_LIST, connected_sta_list_t, AUTO)


PB_BIND(CTRL_MSG_REQ_GET_MAC_ADDRESS, ctrl_msg_req_get_mac_address_t, AUTO)


PB_BIND(CTRL_MSG_RESP_GET_MAC_ADDRESS, ctrl_msg_resp_get_mac_address_t, AUTO)


PB_BIND(CTRL_MSG_REQ_GET_MODE, ctrl_msg_req_get_mode_t, AUTO)


PB_BIND(CTRL_MSG_RESP_GET_MODE, ctrl_msg_resp_get_mode_t, AUTO)


PB_BIND(CTRL_MSG_REQ_SET_MODE, ctrl_msg_req_set_mode_t, AUTO)


PB_BIND(CTRL_MSG_RESP_SET_MODE, ctrl_msg_resp_set_mode_t, AUTO)


PB_BIND(CTRL_MSG_REQ_GET_STATUS, ctrl_msg_req_get_status_t, AUTO)


PB_BIND(CTRL_MSG_RESP_GET_STATUS, ctrl_msg_resp_get_status_t, AUTO)


PB_BIND(CTRL_MSG_REQ_SET_MAC_ADDRESS, ctrl_msg_req_set_mac_address_t, AUTO)


PB_BIND(CTRL_MSG_RESP_SET_MAC_ADDRESS, ctrl_msg_resp_set_mac_address_t, AUTO)


PB_BIND(CTRL_MSG_REQ_GET_AP_CONFIG, ctrl_msg_req_get_ap_config_t, AUTO)


PB_BIND(CTRL_MSG_RESP_GET_AP_CONFIG, ctrl_msg_resp_get_ap_config_t, AUTO)


PB_BIND(CTRL_MSG_REQ_CONNECT_AP, ctrl_msg_req_connect_ap_t, AUTO)


PB_BIND(CTRL_MSG_RESP_CONNECT_AP, ctrl_msg_resp_connect_ap_t, AUTO)


PB_BIND(CTRL_MSG_REQ_GET_SOFT_AP_CONFIG, ctrl_msg_req_get_soft_ap_config_t, AUTO)


PB_BIND(CTRL_MSG_RESP_GET_SOFT_AP_CONFIG, ctrl_msg_resp_get_soft_ap_config_t, AUTO)


PB_BIND(CTRL_MSG_REQ_START_SOFT_AP, ctrl_msg_req_start_soft_ap_t, AUTO)


PB_BIND(CTRL_MSG_RESP_START_SOFT_AP, ctrl_msg_resp_start_soft_ap_t, AUTO)


PB_BIND(CTRL_MSG_REQ_SCAN_RESULT, ctrl_msg_req_scan_result_t, AUTO)


PB_BIND(CTRL_MSG_RESP_SCAN_RESULT, ctrl_msg_resp_scan_result_t, 2)


PB_BIND(CTRL_MSG_REQ_SOFT_AP_CONNECTED_STA, ctrl_msg_req_soft_ap_connected_sta_t, AUTO)


PB_BIND(CTRL_MSG_RESP_SOFT_AP_CONNECTED_STA, ctrl_msg_resp_soft_ap_connected_sta_t, 2)


PB_BIND(CTRL_MSG_REQ_OTA_BEGIN, ctrl_msg_req_ota_begin_t, AUTO)


PB_BIND(CTRL_MSG_RESP_OTA_BEGIN, ctrl_msg_resp_ota_begin_t, AUTO)


PB_BIND(CTRL_MSG_REQ_OTA_WRITE, ctrl_msg_req_ota_write_t, AUTO)


PB_BIND(CTRL_MSG_RESP_OTA_WRITE, ctrl_msg_resp_ota_write_t, AUTO)


PB_BIND(CTRL_MSG_REQ_OTA_END, ctrl_msg_req_ota_end_t, AUTO)


PB_BIND(CTRL_MSG_RESP_OTA_END, ctrl_msg_resp_ota_end_t, AUTO)


PB_BIND(CTRL_MSG_REQ_VENDOR_IE_DATA, ctrl_msg_req_vendor_ie_data_t, AUTO)


PB_BIND(CTRL_MSG_REQ_SET_SOFT_AP_VENDOR_SPECIFIC_IE, ctrl_msg_req_set_soft_ap_vendor_specific_ie_t, AUTO)


PB_BIND(CTRL_MSG_RESP_SET_SOFT_AP_VENDOR_SPECIFIC_IE, ctrl_msg_resp_set_soft_ap_vendor_specific_ie_t, AUTO)


PB_BIND(CTRL_MSG_REQ_SET_WIFI_MAX_TX_POWER, ctrl_msg_req_set_wifi_max_tx_power_t, AUTO)


PB_BIND(CTRL_MSG_RESP_SET_WIFI_MAX_TX_POWER, ctrl_msg_resp_set_wifi_max_tx_power_t, AUTO)


PB_BIND(CTRL_MSG_REQ_GET_WIFI_CURR_TX_POWER, ctrl_msg_req_get_wifi_curr_tx_power_t, AUTO)


PB_BIND(CTRL_MSG_RESP_GET_WIFI_CURR_TX_POWER, ctrl_msg_resp_get_wifi_curr_tx_power_t, AUTO)


PB_BIND(CTRL_MSG_REQ_CONFIG_HEARTBEAT, ctrl_msg_req_config_heartbeat_t, AUTO)


PB_BIND(CTRL_MSG_RESP_CONFIG_HEARTBEAT, ctrl_msg_resp_config_heartbeat_t, AUTO)


PB_BIND(CTRL_MSG_EVENT_ESP_INIT, ctrl_msg_event_esp_init_t, AUTO)


PB_BIND(CTRL_MSG_EVENT_HEARTBEAT, ctrl_msg_event_heartbeat_t, AUTO)


PB_BIND(CTRL_MSG_EVENT_STATION_DISCONNECT_FROM_AP, ctrl_msg_event_station_disconnect_from_ap_t, AUTO)


PB_BIND(CTRL_MSG_EVENT_STATION_DISCONNECT_FROM_ESP_SOFT_AP, ctrl_msg_event_station_disconnect_from_esp_soft_ap_t, AUTO)


PB_BIND(CTRL_MSG, ctrl_msg_t, 2)












